In [2]:
import numpy as np

In [10]:
A1 = np.array([1,2,3,4,5])
A1

array([1, 2, 3, 4, 5])

In [12]:
A1.ndim

1

In [14]:
A1.dtype

dtype('int32')

In [16]:
A1.shape

(5,)

In [18]:
A1.size

5

In [24]:
A1.itemsize*A1.size

20

In [40]:
A2 = np.array([[1,2,3],[4,5,6],[7,8,9]], dtype = float)
A2

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [30]:
A2.ndim

2

In [32]:
A2.shape

(3, 3)

In [34]:
A2.size

9

In [36]:
A2.dtype

dtype('int32')

In [42]:
A2.size*A2.itemsize

72

In [64]:
A3 = np.zeros(9)
A3

array([0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [66]:
A3.reshape(3,3,3)

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [70]:
A4 = np.ones()
A4

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [72]:
A4.ndim

1

In [82]:
A5 = A4.reshape(3,3,3)
A5

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [84]:
A5.ndim

3

In [88]:
A6 = np.zeros(((3,3,3)))
A6

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [96]:
A7 = np.arange(100) # Index starts from 0, so the last value get excluded
A7

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [100]:
A8 = np.arange(50,100) 
A8

array([50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66,
       67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83,
       84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [104]:
A9 = np.arange(50,100,2) #This gives step size
A9

array([50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82,
       84, 86, 88, 90, 92, 94, 96, 98])

In [110]:
A10 = np.linspace(0,100,51)
A10

array([  0.,   2.,   4.,   6.,   8.,  10.,  12.,  14.,  16.,  18.,  20.,
        22.,  24.,  26.,  28.,  30.,  32.,  34.,  36.,  38.,  40.,  42.,
        44.,  46.,  48.,  50.,  52.,  54.,  56.,  58.,  60.,  62.,  64.,
        66.,  68.,  70.,  72.,  74.,  76.,  78.,  80.,  82.,  84.,  86.,
        88.,  90.,  92.,  94.,  96.,  98., 100.])

In [114]:
A11 = np.linspace(1,5,5)
A11

array([1., 2., 3., 4., 5.])

In [118]:
A12 = np.zeros(((3,3,3)))
A12

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [122]:
A13 = A12.ravel() # This converts any dimesnion into 1 dimension
A13

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [126]:
A14 = np.arange(50,100)
A14

array([50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66,
       67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83,
       84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [130]:
A14.min()

50

In [132]:
A14.max()

99

In [134]:
A14.sum()

3725

In [136]:
A15 = np.ones((2,5))
A15

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [138]:
A15.sum(axis=1) #Row wise

array([5., 5.])

In [140]:
A15.sum(axis=0) #Column wise

array([2., 2., 2., 2., 2.])

In [142]:
np.sqrt(2)

1.4142135623730951

In [146]:
np.cbrt(27)

3.0

In [148]:
A16 = np.arange(3,28,3)
A16

array([ 3,  6,  9, 12, 15, 18, 21, 24, 27])

In [150]:
np.cbrt(A16)

array([1.44224957, 1.81712059, 2.08008382, 2.28942849, 2.46621207,
       2.62074139, 2.75892418, 2.88449914, 3.        ])

In [152]:
np.std(A16)

7.745966692414834

In [154]:
np.var(A16)

60.0

In [156]:
np.mean(A16)

15.0

In [186]:
A17 = np.arange(1,11)
A18 = np.arange(11,21)

In [188]:
A19 = A17.reshape(2,5)
A20 = A18.reshape(2,5)
A19

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [190]:
A20

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [192]:
A19 + A20

array([[12, 14, 16, 18, 20],
       [22, 24, 26, 28, 30]])

In [194]:
A20-A19

array([[10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10]])

In [196]:
A19*A20

array([[ 11,  24,  39,  56,  75],
       [ 96, 119, 144, 171, 200]])

In [198]:
A19/A20

array([[0.09090909, 0.16666667, 0.23076923, 0.28571429, 0.33333333],
       [0.375     , 0.41176471, 0.44444444, 0.47368421, 0.5       ]])

In [200]:
A19.dot(A20)

ValueError: shapes (2,5) and (2,5) not aligned: 5 (dim 1) != 2 (dim 0)