# Slicing

In [2]:
import numpy as np

In [6]:
A1 = np.array([1,2,3,4,5])
A1

array([1, 2, 3, 4, 5])

In [14]:
A1[0]

1

In [16]:
A1[2:4]

array([3, 4])

In [23]:
A2 = np.array([[5,10,15,20,25],[30,35,40,45,50],[55,60,65,70,75]])
A2

array([[ 5, 10, 15, 20, 25],
       [30, 35, 40, 45, 50],
       [55, 60, 65, 70, 75]])

In [25]:
A2[0,0]

5

In [29]:
A2[0:2,2:4]

array([[15, 20],
       [40, 45]])

In [31]:
A2[:,:]

array([[ 5, 10, 15, 20, 25],
       [30, 35, 40, 45, 50],
       [55, 60, 65, 70, 75]])

In [33]:
A2[:,-1]

array([25, 50, 75])

In [37]:
A2[:,3:5]

array([[20, 25],
       [45, 50],
       [70, 75]])

# Iterating

In [40]:
A3 = np.array([1,2,3,4,5])
for a in A3:
    print(a)

1
2
3
4
5


In [42]:
A4 = np.array([[1,2,3,4,5],[6,7,8,9,10]])
for a in A4:
    print(a)

[1 2 3 4 5]
[ 6  7  8  9 10]


In [44]:
A5 = np.array([[[1,2,3,4,5],[6,7,8,9,10]]])
for a in A5:
    print(a)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [48]:
for a in A5.flat:
    print(a)

1
2
3
4
5
6
7
8
9
10


# Stacking

In [53]:
A6 = np.arange(6).reshape(2,3)
A6

array([[0, 1, 2],
       [3, 4, 5]])

In [57]:
A7 = np.arange(6,12).reshape(2,3)
A7

array([[ 6,  7,  8],
       [ 9, 10, 11]])

In [65]:
np.vstack((A6,A7))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [67]:
np.hstack((A6,A7))

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

In [89]:
A8 = np.arange((48)).reshape(2,24)
A8

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39,
        40, 41, 42, 43, 44, 45, 46, 47]])

In [95]:
np.vsplit(A8,2)

[array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
         16, 17, 18, 19, 20, 21, 22, 23]]),
 array([[24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39,
         40, 41, 42, 43, 44, 45, 46, 47]])]

In [97]:
np.hsplit(A8,4)

[array([[ 0,  1,  2,  3,  4,  5],
        [24, 25, 26, 27, 28, 29]]),
 array([[ 6,  7,  8,  9, 10, 11],
        [30, 31, 32, 33, 34, 35]]),
 array([[12, 13, 14, 15, 16, 17],
        [36, 37, 38, 39, 40, 41]]),
 array([[18, 19, 20, 21, 22, 23],
        [42, 43, 44, 45, 46, 47]])]

# Boolean Indexing

In [102]:
A9 = np.arange(15).reshape(3,5)
A9

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [104]:
A10 = A9>7

In [106]:
A10

array([[False, False, False, False, False],
       [False, False, False,  True,  True],
       [ True,  True,  True,  True,  True]])

In [110]:
A9[A10]

array([ 8,  9, 10, 11, 12, 13, 14])

In [114]:
A9[A10] = -99
A9

array([[  0,   1,   2,   3,   4],
       [  5,   6,   7, -99, -99],
       [-99, -99, -99, -99, -99]])