In [2]:
import numpy as np

In [6]:
Arr = np.arange(15).reshape(3,5)
Arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [8]:
for a in Arr:
    print(a)

[0 1 2 3 4]
[5 6 7 8 9]
[10 11 12 13 14]


In [10]:
for a in Arr.flat:
    print(a)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14


In [12]:
for a in np.nditer(Arr):
    print(a)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14


In [36]:
for a in np.nditer(Arr, flags = ['external_loop']):
    print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
